# Generated by Django 4.0.5 on 2022-06-10 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nginx', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nginx',
            options={'permissions': [('can_access_jackett', 'Can access Jackett'), ('can_access_lidarr', 'Can access Lidarr'), ('can_access_nextcloud', 'Can access Nextcloud'), ('can_access_qbittorrent', 'Can access QBittorrent'), ('can_access_radarr', 'Can access Radarr'), ('can_access_sonarr', 'Can access Sonarr')]},
        ),
    ]
