# Generated by Django 4.0.5 on 2022-06-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharex', '0003_alter_shareximage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareximage',
            name='image',
            field=models.ImageField(upload_to='sharex'),
        ),
    ]
