# Generated by Django 4.0.5 on 2022-06-10 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareximage',
            name='uploader',
        ),
    ]
