# Generated by Django 4.0.5 on 2022-06-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nginx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_access_sonarr', 'Can access Sonarr'), ('can_access_radarr', 'Can access Radarr'), ('can_access_lidarr', 'Can access Lidarr'), ('can_access_qbittorrent', 'Can access QBittorrent')],
            },
        ),
    ]
